### ISSUE TITLE
Using mouse to select text when content is bigger than the view area

### ISSUE THREAD

**Issue by TsuiTiVadalon** [ViniBZ/SoilFramework#2]
When text content goes beyond view size and the scrollbar is showing, if you do mouse left down and move down, it selects the text and the view moves as the cursor gets closer to the bottom of the view, as the view moves the beginning of the selection resets to the current cursor position corresponding to where the mouse was pressed.

**Comment by ViniBZ** [comment]
Your fix will do.

**Comment by ViniBZ** [comment]
I'm closing this since the last merge solved it.
